image:
  file: .gitpod.Dockerfile
tasks:
  - name: Starting Project
    init: composer create-project laravel/laravel:^8.0 laravel &&
      mkdir -p laravel/packages/skijasi/content-module &&
      mv {,.}* laravel/packages/skijasi/content-module 2>/dev/null; true &&
      cd laravel/packages/skijasi &&
      git clone --branch 2.x --single-branch https://github.com/nadzorservera-croatia/skijasi.git core &&
      cd ../../ &&
      cp packages/skijasi/content-module/.gitpod/AppServiceProvider.php app/Providers/AppServiceProvider.php &&
      cp packages/skijasi/content-module/.gitpod/app.php config/app.php &&
      cp packages/skijasi/content-module/.gitpod/composer.json composer.json &&
      cp packages/skijasi/content-module/.gitpod/webpack.mix.js webpack.mix.js &&
      cp .env.example .env &&
      composer update &&
      php artisan key:generate &&
      mysql -u root -e "create database laravel"
    command: php artisan skijasi:setup --force &&
      php artisan skijasi-content:setup &&
      sed -i 's/http:\/\/localhost//g' .env &&
      sed -i 's/FILESYSTEM_DRIVER=local/FILESYSTEM_DRIVER=public/g' .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      sed -i 's/MIX_DEFAULT_MENU=general/MIX_DEFAULT_MENU=general,content-module/g' .env &&
      sed -i 's/MIX_SKIJASI_MENU=${MIX_DEFAULT_MENU}/MIX_SKIJASI_MENU=${MIX_DEFAULT_MENU},content-module/g' .env &&
      echo -e "\nMIX_SKIJASI_PLUGINS=content-module" >> .env &&
      php artisan migrate &&
      php artisan db:seed --class="Database\Seeders\Skijasi\SkijasiSeeder" &&
      php artisan db:seed --class="Database\Seeders\Skijasi\Content\SkijasiContentModuleSeeder" &&
      php artisan storage:link &&
      php artisan migrate &&
      npm install &&
      php artisan skijasi:admin admin@admin.com --name=admin --username=admin --password=admin --confirm_password=admin --create && 
      npm run dev &&
      php artisan serve --host=0.0.0.0
ports:
  - port: 8000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer
    - PKief.material-icon-theme
